# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'articles'
    label: 'Articles'
    folder: '_posts/'
    editor:
      preview: false
    files:
      - label: 'Talks'
        name: 'talks'
        file: '2016-03-21-foredrag.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Research'
        name: 'research'
        file: '2018-05-27-research-papers.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'html' }
