# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'articles'
    label: 'Articles'
    editor:
      preview: false
    files:
      - label: 'Talks'
        name: 'talks'
        file: '_posts/2016-03-21-foredrag.html'
        fields:
          - { label: 'Body', name: 'body', widget: 'code' }
      - label: 'Research'
        name: 'research'
        file: '_posts/2018-05-27-research-papers.html'
        fields:
          - { label: 'Body', name: 'body', widget: 'code' }
